### ISSUE TITLE
Problem with ARAP parameterization code (Chapter 4 in the tutorial)

### ISSUE THREAD

**Issue by r03ert0** [libigl/libigl-python-bindings#30]
I'm trying to run the code in chapter 4, for arap parameterization. All this first part is ok:
```
v, f  = igl.read_triangle_mesh(os.path.join(root_folder, "data", "camelhead.off"))
## Find the open boundary
bnd = igl.boundary_loop(f)
## Map the boundary to a circle, preserving edge proportions
bnd_uv = igl.map_vertices_to_circle(v, bnd)
## Harmonic parametrization for the internal vertices
uv = igl.harmonic_weights(v, f, bnd, bnd_uv, 1)
arap = igl.ARAP(v, f, 2, np.zeros((0)))
```

However, this last line fails:
```
uva = arap.solve(np.zeros((0, 0)), uv)
```

This is the error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-162-15f3df1c16bf> in <module>
----> 1 uva = arap.solve(np.zeros((0, 0)), uv)

ValueError: Parameter bc has invalid shape at dimension 1, expected bc.shape[1] = 2 but got bc.shape = [0, 0]
```

Thanks in advance for your help!

**Comment by r03ert0** [comment]
I tried executing directly from the `tutorial.ipynb` notebook. The Harmonic parametrization demo worked; the Least squares conformal maps as well; but the As-rigid-as-possible parametrization demo failed:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-71f621d0b0af> in <module>
     11 
     12 arap = igl.ARAP(v, f, 2, np.zeros((0)))
---> 13 uva = arap.solve(np.zeros((0, 0)), uv)
     14 
     15 p = plot(v, f, uv=uva, shading={"wireframe": False, "flat": False}, return_plot=True)

ValueError: Parameter bc has invalid shape at dimension 1, expected bc.shape[1] = 2 but got bc.shape = [0, 0]
```

**Comment by teseoch** [comment]
which version of igl in python are you using?

It is something that I fixed recently.

If you are using conda, try "reinstalling the package", this should trigger an update

**Comment by r03ert0** [comment]
hello!
I was still using version 0.3.1
Now I installed version 0.4, and the error is still the same:

```
ValueError                                Traceback (most recent call last)
<ipython-input-4-71f621d0b0af> in <module>
     11 
     12 arap = igl.ARAP(v, f, 2, np.zeros((0)))
---> 13 uva = arap.solve(np.zeros((0, 0)), uv)
     14 
     15 p = plot(v, f, uv=uva, shading={"wireframe": False, "flat": False}, return_plot=True)

ValueError: Parameter bc has invalid shape at dimension 1, expected bc.shape[1] = 2 but got bc.shape = [0, 0]
```

and

```
!conda list|grep igl
igl                       0.4              py37h8bd51ef_1    conda-forge
```
(the previous code in chapter 4 works ok)

**Comment by fwilliams** [comment]
Change `np.zeros((0, 0)` to `np.zeros((0, 2))`. It looks like we always expect the parameter `bc` to have 2 columns. We should fix the error check in the binding if empty arrays are allowed.

**Comment by teseoch** [comment]
I just pushed a new release, 4.1.1 it should fix this issue.

**Note** that it takes about 1h from now to have the unix releases and about 2h for windows.
